ShoesSHop/Controllers/CartController.cs
using ShoesSHop.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGrease;

namespace ShoesSHop.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        private string CartSession = "CartSession";
        Model1 db = new Model1();
        public List<Size_SP_Chitietdonhang> GetList()
        {
            var query = from sp in db.sanphams
                        join size in db.kichcoes on sp.idkichco equals size.id
                        join ctdh in db.chitietdonhangs on sp.id equals ctdh.idsanpham
                        select new Size_SP_Chitietdonhang
                        {
                            tensanpham = sp.tensanpham,
                            giaban = sp.giaban,
                            hinhanh = sp.hinhanh,
                            kichco1 = size.kichco1,
                            soluong = ctdh.soluong
                    
                        };
            return query.ToList();
                        
        }
        public double? TinhTong(List<Size_SP_Chitietdonhang> list)
        {
            return list.Sum(x => x.giaban * x.soluong);
        }

        public ActionResult Cart1()
        {
            var cart = Session[CartSession];
            var list = new List<Size_SP_Chitietdonhang>();

            list = GetList();
            ViewBag.TongTien = TinhTong(list);
            if (cart != null)
            {
                list = (List<Size_SP_Chitietdonhang>)cart;
                list = GetList();
            }
           
            return View(list);
        }
        public ActionResult Cart2()
        {
            return View();
        }
        public ActionResult Cart3()
        {
            return View();
        }
        public ActionResult CartAddress()
        {
            return View();
        }
        public ActionResult Message()
        {
            return View();
        }
        public ActionResult AddItem(int productId, int quantity)
        {
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<chitietdonhang>)cart;
                if(list.Exists(x=>x.idsanpham == productId))
                {
                    foreach (var item in list)
                    {
                        if (item.idsanpham == productId)
                        {
                            item.soluong += quantity;
                        }
                    }
                }
                else
                {
                    // tao moi doi tuong cart item
                    var item = new chitietdonhang();
                    item.idsanpham = productId;
                    item.soluong = quantity;
                    list.Add(item);
                }
                
            }
            else
            {
                var item = new chitietdonhang();
                item.idsanpham = productId;
                item.soluong = quantity;
                var list = new List<chitietdonhang>();
                Session[CartSession] = list;
            }
            return RedirectToAction("Cart2");
        }
    }
}

ShoesSHop/Views/Cart/Cart1.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}
@using ShoesSHop.Models;
@model List<Size_SP_Chitietdonhang>


<div class="l-layout">
    <div class="container">
        <div class="c-browse-title"><h1>Giỏ hàng</h1></div>
        <div class="c-cart-box">
            <div class="row">
                <div class="col-lg-8 col-xl-8">
                    <div class="c-cart-table">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="col1">Sản phẩm<span class="c-cart-table__col-pc">Giá</span></th>
                                    <th class="col2 text-right">Thành tiền</th>
                                </tr>
                            </thead>
                            
                            <tbody>
                                
                                @foreach (var item in Model)
                                {
                                    var ThanhTien = @item.soluong * @item.giaban;
                                    <tr>
                                        <td class="col1">
                                            <div class="b-grid">
                                                <div class="b-grid__img"><a href="#"><img src="@item.hinhanh" alt="product" /></a></div>
                                                <div class="b-grid__content">
                                                    <ul class="clearfix">
                                                        <li>
                                                            <div class="b-grid__row"><a class="b-grid__title" href="#"></a>@item.tensanpham</div>
                                                            <div class="b-grid__row">@item.kichco1</div>
                                                        </li>
                                                        <li>
                                                            <div class="b-grid__row"><span class="price" id="price"+@item.idsanpham  >@item.giaban</span></div>
                                                        </li>
                                                        <li class="full">
                                                            <div class="b-grid__row"><label>Số lượng</label><input class="form-control b-grid__number" type="number" min="0" value="@item.soluong" /></div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="col2">
                                            <span class="price">@ThanhTien</span>
                                            <button class="remove" type="button" name=""><i class="far fa-trash-alt"></i></button>
                                        </td>
                                    </tr>
                                }



               


                            </tbody>
                            <tfoot>
                                <tr><td colspan="2" class="text-right"><button type="button" class="btn btn-secondary">Cập nhập giỏ hàng</button></td></tr>
                            </tfoot>
                        </table>
                    </div><!-- c-cart-table -->
                    <div class="c-checkout-box">
                        <div class="c-checkout-box__title">Nhập mã giảm giá</div>
                        <div class="c-checkout-box__content">
                            <div class="c-coupon-box">
                                <div class="input-group">
                                    <input type="text" name="" class="form-control" placeholder="Mã giảm giá" />
                                    <div class="input-group-append">
                                        <button class="btn btn-secondary" type="button">Áp dụng</button>
                                    </div>
                                </div>
                            </div>
                        </div><!-- c-checkout-box__content -->
                    </div><!-- c-checkout-box -->
                </div><!-- col -->
                <div class="col-lg-4 col-xl-3 ml-auto">
                    <div class="c-cart-total">
                        <div class="c-cart-total__name">3 sản phẩm</div>
                        <div class="c-cart-total__row clearfix">
                            <span class="label">Tổng</span>
                            <span class="price">@ViewBag.TongTien</span>
                        </div>
                        <div class="c-cart-total__row clearfix">
                            <div class="text-right">
                                <p>Đã bao gồm thuế VAT 10%</p>
                            </div>
                            <div class="c-cart-total__btn">
                                <a class="btn btn-light text-uppercase is-cicle" href="@Url.Action("Index","Home")">Mua thêm</a>
                                <a class="btn btn-primary text-uppercase is-cicle" href="@Url.Action("CartAddress","Cart")">Thanh toán</a>
                            </div>
                        </div>
                    </div><!-- c-cart-total -->
                    <div class="c-cart-hotline">Hotline: 0888 230 788</div>
                </div><!-- col -->
            </div><!-- row -->
        </div><!-- c-cart-box -->
    </div><!-- container -->
</div><!-- l-layout -->

ShoesSHop/Views/Cart/Cart2.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="l-layout">
    <div class="container">
        <div class="c-browse-title"><h1>Giỏ hàng</h1></div>
        <div class="c-cart-box">
            <div class="row">
                <div class="col-lg-8 col-xl-8">
                    <div class="c-checkout-box">
                        <div class="c-checkout-box__title">Địa chỉ giao hàng</div>
                        <div class="c-checkout-box__content">
                            <div class="b-form">
                                <div class="row form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Họ của bạn <span class="text-danger">*</span></label>
                                            <input type="text" required class="form-control" placeholder="VD: Nguyễn Văn" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Tên của bạn <span class="text-danger">*</span></label>
                                            <input type="text" required class="form-control" placeholder="VD: A" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Email của bạn <span class="text-danger">*</span></label>
                                            <input type="text" required class="form-control" placeholder="VD: nguyenvana@gmail.com" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Số điện thoại <span class="text-danger">*</span></label>
                                            <input type="text" required class="form-control" placeholder="VD: 0912345678" />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Tỉnh/ Thành phố <span class="text-danger">*</span></label>
                                    <input type="text" required class="form-control" placeholder="VD: Hà Nội" />
                                </div>
                                <div class="form-group _error">
                                    <label>Địa chỉ giao hàng <span class="text-danger">*</span></label>
                                    <input type="text" required class="form-control" placeholder="VD: Số 1 Trần Duy Hưng" />
                                    <div class="field-error">Địa chỉ giao hàng để trống.</div>
                                </div>
                                <div class="form-group">
                                    <label>Lưu ý</label>
                                    <textarea required="false" class="form-control" rows="3" placeholder="VD: Giao trong giờ hành chính"></textarea>
                                </div>
                            </div>
                        </div><!-- c-checkout-box__content -->
                    </div><!-- c-checkout-box -->
                    <div class="c-checkout-box">
                        <div class="c-checkout-box__title">Phương thức vận chuyển</div>
                        <div class="c-checkout-box__content">
                            <form class="b-form">
                                <div class="check-box-row">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                                        <label class="form-check-label" for="inlineRadio1">
                                            <b class="check-box-row__title">Giao hàng miễn phí</b>
                                            <span class="check-box-row__price">0 Đ</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="c-checkout-button"><a class="btn btn-primary btn-lg text-uppercase" href="@Url.Action("CartAddress","Cart")">Tiếp theo</a></div>
                            </form>
                        </div><!-- c-checkout-box__content -->
                    </div><!-- c-checkout-box -->
                </div><!-- col -->
                <div class="col-lg-4 col-xl-3 ml-auto">
                    <div class="c-cart-total">
                        <div class="c-cart-total__name">3 sản phẩm</div>
                        <div class="c-cart-total__row clearfix">
                            <div class="c-cart-small">
                                <div class="b-grid">
                                    <div class="b-grid__img"><a href="#"><img src="upload/product_1.jpg" alt="image" /></a></div>
                                    <div class="b-grid__content">
                                        <div class="b-grid__row">
                                            <a class="b-grid__title" href="#">Combo 5 khăn tắm Hàn Quốc nhiều màu sắc</a>
                                            <span class="b-grid__pro">Size 42 x 29.7 cm</span>
                                        </div>
                                        <div class="b-grid__row"><span class="b-grid__price">3.200.000 VND x 1</span></div>
                                    </div>
                                </div><!-- b-grid -->
                                <div class="b-grid">
                                    <div class="b-grid__img"><a href="#"><img src="upload/product_2.jpg" alt="image" /></a></div>
                                    <div class="b-grid__content">
                                        <div class="b-grid__row">
                                            <a class="b-grid__title" href="#">Đầm Jean Khóa Kéo THỜI TRANG TỪ 42-70KG đủ size m,l,xl,xxl CHJ1 - CHJ1</a>
                                            <span class="b-grid__pro">Size 42 x 29.7 cm</span>
                                        </div>
                                        <div class="b-grid__row"><span class="b-grid__price">3.200.000 VND x 1</span></div>
                                    </div>
                                </div><!-- b-grid -->
                                <div class="b-grid">
                                    <div class="b-grid__img"><a href="#"><img src="upload/product_3.jpg" alt="image" /></a></div>
                                    <div class="b-grid__content">
                                        <div class="b-grid__row">
                                            <a class="b-grid__title" href="#">Xịt Chống Nắng Hàn Quốc Sun Screen V7 200ml - sunscreen22</a>
                                            <span class="b-grid__pro">Size 42 x 29.7 cm</span>
                                        </div>
                                        <div class="b-grid__row"><span class="b-grid__price">3.200.000 VND x 1</span></div>
                                    </div>
                                </div><!-- b-grid -->
                            </div><!-- c-cart-small -->
                        </div>
                        <div class="c-cart-total__row clearfix">
                            <p>
                                <span class="label">Giảm trừ</span>
                                <span class="price">-</span>
                            </p>
                        </div>
                        <div class="c-cart-total__row clearfix">
                            <span class="label">Tổng</span>
                            <span class="price">8.700.000 VND</span>
                        </div>
                    </div><!-- c-cart-total -->
                </div><!-- col -->
            </div><!-- row -->
        </div><!-- c-cart-box -->
    </div><!-- container -->
</div><!-- l-layout -->

ShoesSHop/Views/Cart/CartAddress.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="l-layout">
    <div class="container">
        <div class="c-browse-title"><h1>Giỏ hàng</h1></div>
        <div class="c-cart-box">
            <div class="row">
                <div class="col-lg-8 col-xl-8">
                    <div class="c-checkout-box">
                        <div class="c-checkout-box__title">Địa chỉ giao hàng</div>
                        <div class="c-checkout-box__content">
                            <div class="c-address-list clearfix">
                                <div class="c-address-item selected-item">
                                    Veronica Costello
                                    <br />6146 Honey Bluff Parkway
                                    <br />Calder, Michigan 49628-7978
                                    <br />United States
                                    <br /><a href="#">(555) 229-3326</a>
                                </div><!-- c-address-item -->
                                <div class="c-address-item not-selected-item">
                                    Veronica Costello
                                    <br />823 41st street
                                    <br />Brooklyn, New York 11232
                                    <br />United States
                                    <br /><a href="#">5757402615</a>
                                    <br /><button type="button" class="btn btn-primary btn-sm">Chọn</button>
                                </div><!-- c-address-item -->
                                <div class="c-address-item not-selected-item">
                                    Veronica Costello
                                    <br />dsfsdfsdf
                                    <br />fdsfsdf, Federated States Of Micronesia 12345-6789
                                    <br />United States
                                    <br /><a href="#">324234</a>
                                    <br /><button type="button" class="btn btn-primary btn-sm">Chọn</button>
                                </div><!-- c-address-item -->
                            </div><!-- c-address-list -->
                            <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAddress"  id="myButton" >Thêm địa chỉ</button>
                        </div><!-- c-checkout-box__content -->
                    </div><!-- c-checkout-box -->
                    <div class="c-checkout-box">
                        <div class="c-checkout-box__title">Phương thức vận chuyển</div>
                        <div class="c-checkout-box__content">
                            <form class="b-form">
                                <div class="check-box-row">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                                        <label class="form-check-label" for="inlineRadio1">
                                            <b class="check-box-row__title">Giao hàng miễn phí</b>
                                            <span class="check-box-row__price">0 Đ</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="c-checkout-button"><a class="btn btn-primary btn-lg text-uppercase" href="@Url.Action("Cart3","Cart")">Tiếp theo</a></div>
                            </form>
                        </div><!-- c-checkout-box__content -->
                    </div><!-- c-checkout-box -->
                </div><!-- col -->
                <div class="col-lg-4 col-xl-3 ml-auto">
                    <div class="c-cart-total">
                        <div class="c-cart-total__name">3 sản phẩm</div>
                        <div class="c-cart-total__row clearfix">
                            <div class="c-cart-small">
                                <div class="b-grid">
                                    <div class="b-grid__img"><a href="#"><img src="upload/product_1.jpg" alt="image" /></a></div>
                                    <div class="b-grid__content">
                                        <div class="b-grid__row">
                                            <a class="b-grid__title" href="#">Combo 5 khăn tắm Hàn Quốc nhiều màu sắc</a>
                                            <span class="b-grid__pro">Size 42 x 29.7 cm</span>
                                        </div>
                                        <div class="b-grid__row"><span class="b-grid__price">3.200.000 VND x 1</span></div>
                                    </div>
                                </div><!-- b-grid -->
                                <div class="b-grid">
                                    <div class="b-grid__img"><a href="#"><img src="upload/product_2.jpg" alt="image" /></a></div>
                                    <div class="b-grid__content">
                                        <div class="b-grid__row">
                                            <a class="b-grid__title" href="#">Đầm Jean Khóa Kéo THỜI TRANG TỪ 42-70KG đủ size m,l,xl,xxl CHJ1 - CHJ1</a>
                                            <span class="b-grid__pro">Size 42 x 29.7 cm</span>
                                        </div>
                                        <div class="b-grid__row"><span class="b-grid__price">3.200.000 VND x 1</span></div>
                                    </div>
                                </div><!-- b-grid -->
                                <div class="b-grid">
                                    <div class="b-grid__img"><a href="#"><img src="upload/product_3.jpg" alt="image" /></a></div>
                                    <div class="b-grid__content">
                                        <div class="b-grid__row">
                                            <a class="b-grid__title" href="#">Xịt Chống Nắng Hàn Quốc Sun Screen V7 200ml - sunscreen22</a>
                                            <span class="b-grid__pro">Size 42 x 29.7 cm</span>
                                        </div>
                                        <div class="b-grid__row"><span class="b-grid__price">3.200.000 VND x 1</span></div>
                                    </div>
                                </div><!-- b-grid -->
                            </div><!-- c-cart-small -->
                        </div>
                        <div class="c-cart-total__row clearfix">
                            <p>
                                <span class="label">Giảm trừ</span>
                                <span class="price">-</span>
                            </p>
                        </div>
                        <div class="c-cart-total__row clearfix">
                            <span class="label">Tổng</span>
                            <span class="price">8.700.000 VND</span>
                        </div>
                    </div><!-- c-cart-total -->
                </div><!-- col -->
            </div><!-- row -->
        </div><!-- c-cart-box -->
    </div><!-- container -->
</div>

<script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        window.location.href = "/Cart/Cart2";
    };
</script>

ShoesSHop/Views/Cart/Message.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}
<div class="l-layout">
    <div class="container">
        <div class="c-message">
            <div class="c-message__title text-center">Thông báo</div>
            <div class="b-maincontent text-center">
                <p>Đơn hàng bạn vừa mua đã được thêm vào hệ thống</p>
                <p>Vui lòng check thêm email để biết thêm thông tin chi tiết về đơn hàng.</p>
                <p>Hoặc click <a href="#">vào đây</a> để quay lại tiếp tục mua sắm.</p>
            </div><!-- b-maincontent -->
            <div class="c-message__btn text-center"><a class="btn btn-primary" href="@Url.Action("Cart3","Cart")">Quay lại</a></div>
        </div><!-- c-message -->
    </div><!-- container -->
</div><!-- l-layout -->